# Change these first
owner: kuznacic # Your GitHub organization or username, where this repository lives
repo: wtf-uptime # The name of this repository

sites:
  - name: Why The Fuss? Technical Solutions
    url: https://wtftechsolutions.com
  - name: Inside The Mind Of Eric Kuznacic
    url: https://erickuznacic.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.wtftechsolutions.com
  #baseUrl: /wtf-uptime
  logoUrl: https://github.com/kuznacic/wtf-uptime/blob/0a3e96b5c6b8a746b924b92b1d1d2c37437bf91a/assets/WTF-only-with-text-250x92.png
  name: WTF? Hosting Monitoring
  introTitle: "This site is for use by clients of WTF? Hosting."
  introMessage: This page uses **real-time** data from our [GitHub repository](https://github.com/kuznacic/wtf-uptime).
  navbar:
    - title: Status
      href: /
    - title: WTF? Home
      href: https://wtftechsolutions.com/
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
