# Change these first
owner: kuznacic # Your GitHub organization or username, where this repository lives
repo: wtf-uptime # The name of this repository

sites:
  - name: Alive Wellness Group
    url: https://alivewellnessgroup.com
  - name: Badger Hardwood
    url: https://www.badgerwood.com
  - name: Better Brodhead
    url: https://betterbrodhead.org
  - name: Biohackers Fitness
    url: https://biohackersfitness.com
  - name: Biohackers Warehouse
    url: https://biohackerswarehouse.com
  - name: Break-Free Health & Wellness
    url: https://breakfree-healthandwellness.com
  - name: Cecelia's Golf Course
    url: https://ceceliasgolf.com
  - name: Community Foundation of Southern Wisconsin
    url: https://cfsw.org
  - name: CG Ministry
    url: https://www.cgministry-inchrist.com
  - name: Children's Museum of Rock County
    url: https://kidsatplayrc.com
  - name: Colecago
    url: https://blog.colecago.com
  - name: Coming Through The Fog
    url: https://www.comingthroughthefog.com
  - name: Community Action, Inc. (hosted elsewhere)
    url: https://community-action.org
  - name: Community Health Systems
    url: https://www.chsofwi.org
  - name: Cornerstone of Hope
    url: https://csohwi.com
  - name: Crist Real Estate Group
    url: https://cristrealestategroup.com
  - name: Diversity Action Team
    url: https://www.datrockco.org
  - name: Don Vruwink for Assembly
    url: https://donvruwinkforassembly.com
  - name: Earthsong Books and Gifts
    url: https://earthsongbooksandgifts.com
  - name: ECHO of Janesville
    url: https://echojanesville.org
  - name: Foundation for the Preservation of 108 South Jackson
    url: https://www.janesvillewomansclub.com
  - name: Friends of Riverside Park
    url: https://jvlriversidepark.com
  - name: Go Wisconsin Global
    url: https://www.gowisconsinglobal.org
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Grace Evangelical Free Church
    url: https://graceevangelicalfree.org
  - name: HealthNet of Rock County
    url: http://www.healthnet-rock.org
  - name: High Class Grass
    url: https://high-classgrass.com
  - name: HOPE Child & Family Counseling
    url: https://hopechildandfamilycounseling.com
  - name: Hunt-N-Gear
    url: https://huntngearonline.com
  - name: Impact Confections
    url: https://impactconfections.com
  - name: Inside The Mind Of Eric Kuznacic
    url: https://erickuznacic.com
  - name: IV Careers
    url: https://ivcareers.com
  - name: Janesville Lions Club
    url: https://janesvillelions.org
  - name: Jeffris Foundation
    url: https://www.jeffrisfoundation.org
  - name: JLA Architects
    url: https://jla-ap.com
  - name: Ken Johnson DDS
    url: https://www.kenjohnsondds.com
  - name: Ketamine Health Centers
    url: https://ketaminehealthcenters.com
  - name: Leadership Development Academy
    url: http://ldarock.com
  - name: Little Luzon
    url: https://littleluzon.com
  - name: LWML-NID
    url: https://lwmlnid.org
  - name: Maker Matt Home
    url: http://www.makermatthome.com
  - name: Midwest Veterinary Dental Services
    url: https://www.midwestvetdental.com
  - name: Milwaukee Grill
    url: https://milwaukeegrill.com
  - name: New York Juvenile Asylum
    url: https://newyorkjuvenileasylum.com
  - name: Pink Houses
    url: https://pinkhouses.net
  - name: Project 16:49
    url: https://project1649.org
  - name: Quivering Moon
    url: http://www.quiveringmoon.com
  - name: RBG Holiday Light Show
    url: https://rbgholidaylightshow.com
  - name: Rock Co. Historical Society
    url: https://rchs.us
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Rock Co. Rifle & Pistol Club
    url: http://www.rcrpc.com
  - name: Rock County Shot
    url: https://rockcountyshot.com
  - name: Rock Valley HVAC
    url: https://rvhvacinc.com
  - name: Rotary Botanical Gardens
    url: https://rotarybotanicalgardens.org
  - name: SMR Photography
    url: https://www.smrphotography.com
  - name: St. John Lutheran Church
    url: https://www.sjlc-elca.org
  - name: SummerStage of Delafield
    url: https://summerstageofdelafield.org
  - name: Tessagen
    url: http://www.tessagen.com
  - name: The Booch Witch
    url: https://boochwitch.com
  #- name: Thompson's Hemp Co.
  #  url: https://thompsonshempco.com
  - name: Town of Eau Galle
    url: https://www.townofeaugalle.org
  - name: United Way Blackhawk Region
    url: https://liveunitedbr.org
  - name: US Stem Cell Clinic
    url: https://usstemcellclinic.com
  - name: Waukesha Co. Community Foundation
    url: https://waukeshafoundation.org
  - name: WFVC
    url: https://www.wisconsinforvaccinechoice.org
  - name: Why The Fuss? Technical Solutions
    url: https://wtftechsolutions.com
  - name: WTF? Hosting
    url: https://whythefusshosting.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.wtftechsolutions.com
  #baseUrl: /wtf-uptime
  logoUrl: https://github.com/kuznacic/wtf-uptime/blob/0a3e96b5c6b8a746b924b92b1d1d2c37437bf91a/assets/WTF-only-with-text-250x92.png?raw=true
  name: WTF? Hosting Status Monitor
  introTitle: "This site is for WTF? Hosting clients to monitor their website's uptime and other vital metrics."
  introMessage: This page uses **real-time** data from our [GitHub repository](https://github.com/kuznacic/wtf-uptime). Each monitor runs on approximately 5-minute intervals.
  navbar:
    - title: Status Home
      href: /
    - title: WTF? Home
      href: https://wtftechsolutions.com/
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
  js: "function contains(t,n){var e=document.querySelectorAll(t);return Array.prototype.filter.call(e,function(t){return RegExp(n).test(t.textContent)})}window.onload = function() {setTimeout(function(){foundDivsActiveIncidents=contains('section','Active Incidents');foundDivsActiveIncidents[0].remove();foundDivsPastIncidents=contains('section','Past Incidents');foundDivsPastIncidents[0].remove();}, 5000);}"
      
notifications:
  - type: slack
    channel: G6PR66U07

robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
