# Change these first
owner: kuznacic # Your GitHub organization or username, where this repository lives
repo: wtf-uptime # The name of this repository

sites:
  - name: Why The Fuss? Technical Solutions
    url: https://wtftechsolutions.com
  - name: Inside The Mind Of Eric Kuznacic
    url: https://erickuznacic.com
  - name: The Booch Witch
    url: https://boochwitch.com
  - name: Alive Wellness Group
    url: https://alivewellnessgroup.com
  - name: Badger Hardwood
    url: https://www.badgerwood.com
  - name: Better Brodhead
    url: https://betterbrodhead.org
  - name: Biohackers Fitness
    url: https://biohackersfitness.com
  - name: Biohackers Warehouse
    url: https://biohackerswarehouse.com
  - name: Break-Free Health & Wellness
    url: https://breakfree-healthandwellness.com
  - name: Cecelia's Golf Course
    url: https://ceceliasgolf.com
  - name: Community Foundation of Southern Wisconsin
    url: https://cfsw.org
  - name: CG Ministry
    url: https://www.cgministry-inchrist.com
  - name: Children's Museum of Rock County
    url: https://kidsatplayrc.com
  - name: Colecago
    url: https://blog.colecago.com
  - name: Coming Through The Fog
    url: https://www.comingthroughthefog.com
  - name: Community Action, Inc. (hosted elsewhere)
    url: https://community-action.org
  - name: Community Health Systems
    url: https://www.chsofwi.org
  - name: Cornerstone of Hope
    url: https://csohwi.com
  - name: Crist Real Estate Group
    url: https://cristrealestategroup.com
  - name: Diversity Action Team
    url: https://www.datrockco.org
  - name: Don Vruwink for Assembly
    url: https://donvruwinkforassembly.com
  - name: Earthsong Books and Gifts
    url: https://earthsongbooksandgifts.com
  - name: ECHO of Janesville
    url: https://echojanesville.org
  - name: Foundation for the Preservation of 108 South Jackson
    url: https://www.janesvillewomansclub.com
  - name: Friends of Riverside Park
    url: https://jvlriversidepark.com
  - name: Go Wisconsin Global
    url: https://www.gowisconsinglobal.org
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.wtftechsolutions.com
  #baseUrl: /wtf-uptime
  logoUrl: https://github.com/kuznacic/wtf-uptime/blob/0a3e96b5c6b8a746b924b92b1d1d2c37437bf91a/assets/WTF-only-with-text-250x92.png?raw=true
  name: WTF? Hosting Status Monitor
  introTitle: "This site is for WTF? Hosting clients to monitor their website's uptime and other vital metrics."
  introMessage: This page uses **real-time** data from our [GitHub repository](https://github.com/kuznacic/wtf-uptime).
  navbar:
    - title: Status
      href: /
    - title: WTF? Home
      href: https://wtftechsolutions.com/
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
