# Change these first
owner: kuznacic # Your GitHub organization or username, where this repository lives
repo: wtf-uptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Why The Fuss? Technical Solutions
    url: https://wtftechsolutions.com
  - name: Inside The Mind Of Eric Kuznacic
    url: https://erickuznacic.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.wtftechsolutions.com
  #baseUrl: /wtf-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WTF? Hoting Monitoring
  introTitle: "This site is for use only by clients of WTF? Hosting."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/kuznacic/wtf-uptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
